### ISSUE TITLE
ASGIRef 3.4.0 deadlock_context causes exception on threading

### ISSUE THREAD

**Issue by herpolody** [django/asgiref#285] opened 2021-07-26 20:07 UTC
I still can see this issue. I am a noob in channels, just following the tutorials. Today installed channels.
Python 3.8, Django 2.2.6, channels 3.0.4, asgiref 3.4.1

* Tutorial introduction -> no issues, channels is taking care of the http requests
* Tutorial 1: Basic setup -> Ok
* Tutorial 2 : after adding the `websocket` protocol to `asgi.py` **some** static files not loading (some loading others not), error 500 in the server, deadlock error in the Traceback, same symptoms as #275

    As per [rdmrocha](https://github.com/django/asgiref/issues/275#issuecomment-870083420), falling back to the asgiref version 3.3.4 problem is gone, static files loading without errors.

**Comment by carltongibson** [comment] 2021-07-27 12:13
This is a duplicate of https://github.com/django/channels/issues/1722 @herpolody if you'd like to follow there.

**Closed by carltongibson** 2021-07-27 12:13 UTC
