### ISSUE TITLE
The ASGI_THREADS environment variables is not working with Daphne

### ISSUE THREAD

**Issue by shanzi** [django/asgiref#185] opened 2020-08-03 09:39 UTC
We found the ASGI_THREADS environment variables used at the [sync.py#L235](https://github.com/django/asgiref/blob/3.2.10/asgiref/sync.py#L235) won't work with daphne.

The reason might be [daphne/server.py#L128](https://github.com/django/daphne/blob/master/daphne/server.py#L128) called `set_event_loop`. Thus the previous event loop which has a default `ThreadPoolExecutor` was overridden before `__call__`.

Can we fix this issue by checking if the default `ThreadPoolExecutor`  is set?

**Comment by carltongibson** [comment] 2020-08-03 10:37
Duplicate of https://github.com/django/daphne/issues/319 — it's an issue there. 

We need to resolve, probably reverting https://github.com/django/daphne/commit/27f760a8147efd0c2f4cb842cbe9d50cfdf40d46 — but then that recreates https://github.com/django/channels/issues/1374 — so it's currently pending time to think about it. If you'd like to input on https://github.com/django/daphne/issues/319, that would be great.

**Closed by carltongibson** 2020-08-03 10:37 UTC
