### ISSUE TITLE
SSL error 

### ISSUE THREAD

**Issue by hibare** [django/asgiref#128] opened 2019-10-07 13:40 UTC
Throws SSL errors when used in conjugation with a redis instance which uses mutual SSL verification using internal CA signed certs.

Problem reproduce steps:
Install a redis instance which uses mutual authentication using SSL certs.
Use self signed SSL certs.

**Comment by andrewgodwin** [comment] 2019-10-08 05:29
Can we have a bit more information, please? How is this related to `asgiref`?

**Comment by carltongibson** [comment] 2019-10-09 14:22
Duplicate of https://github.com/django/channels/issues/1362. Traceback there points to the need to configure Python's SSL module. Not really an `asgiref` issue.

**Comment by andrewgodwin** [comment] 2019-10-09 14:36
Thanks Carlton! I'll close this one then.

**Closed by andrewgodwin** 2019-10-09 14:36 UTC
Labels: blocked/user-response
